### PR TITLE
 Implemented the date of birth field separation

### PR DESCRIPTION
**Pull request by HelloTiago**
Relates to issue #214. This has been deployed to https://givepanel-dev3.firebaseapp.com

@jonrandahl Please have a look and let me know what you think of the implementation. Also, I'm not super happy with the error messages copy but I couldn't come up with a better one - if you have any ideas please let me know and I'll update it. Thanks!

### CODE REVIEW

**Comment by HelloTiago** [comment]
@jonrandahl I fixed the bug where the alert didn't clear when the validation is resolved, but after merging the latest from staging it looks like a new bug was introduced, where the alert suddenly appears after the form is submitted.

After some debugging, it appears that the state property `isAlertOpen` (along with every other state property that we don't send to the DB) is cleared when the Fundraiser Details are updated. This is, unfortunately, a result of trying to sync the entire state to the DB - anything that's not part of DB will be blown up when we get the data back.

I think we have two options here:
1. Try to maintain (or populate) the `isAlertOpen` state property when the fundraiser details are updated. Unfortunately I couldn't figure out a way to do this without introducing other bugs, but you or @shramee might be able to figure it out. We will however run into this problem whenever we add more properties that need to be maintained in the state but shouldn't be sent to the DB, such as interactive UI components.

2. This is typically the recommended approach, where we store all the Fundraiser details data inside a `fundraiser` (for example) object in the state, and then *only* sync the contents of that array to/from the DB. This would allow us to keep as many properties as we'd like in the state without having to worry about poluting the DB with UI-related state properties, or having to worry about initializing those when we get the data back from the DB. So the state would look something like this (properties abbreviated for the sake of demonstration):

```
this.state = {
  // this is what we sync with the DB
  fundraiser: {
    tooltip: false,
    campaignID: this.props.fundraiser.campaignID,
    notes: this.props.fundraiser.notes,
    owner: {
      name: this.props.fundraiser.owner.name,
      address1: this.props.fundraiser.owner.address1,
    },
    title: this.props.fundraiser.title,
  },
  // and we can keep everything else as part of the state
  isAlertOpen: false,
  alertMessage: 'An error has occurred.',
  // any new UI state properties we need to add in the future would go here
}
```

The latter is something I think I'd need your or @shramee 's help to achieve it since I'm unsure as to how best to tackle the data initialization. Right now we have data coming in/going out/being managed in multiple places (like `manageFundraisers` from `fundraiserActions.js`, `Fundraisers.fundraisers` and `ChronologicalTransactionsData.setup` from `Fundraisers.js`) and I'm still a bit confused about it.

Let me know how you'd like to proceed and we can discuss the next steps.

**Comment by jonrandahl** [comment]
@HelloTiago I completely agree about not polluting the DB with UI state which is why I've approached this in this manner:

https://github.com/NickBurneConsulting-GivePanel/givepanel/blob/2c123a550a3f20ceb86ad356c266783c036fb3c3/client/src/actions/fundraiserActions.js#L175-L187

Thoughts on how we could do the same for this instance?

**Comment by HelloTiago** [comment]
@jonrandahl Right, that's the approach you mentioned on Slack the other day and I followed it. It's implemented here:

https://github.com/NickBurneConsulting-GivePanel/givepanel/blob/e0b35283cfa97e60926acd715cf9e281912ec575/client/src/actions/fundraiserActions.js#L97-L101

And that works well in removing any data we don't want being sent to the DB. However, when the data comes back from the DB (say after we save the fundraiser), the entire state gets blown up and reset to _only_ what comes back from the DB - which doesn't include the UI state properties we had before, and we need them. This isn't a problem in your response form because when the UI state properties are lost all that happens is that the form clears - which is actually a good thing in that case :)

In addition, the current approach has the additional overhead of having to maintain the state "deletes" somewhere else outside the component.

Let's hop on a call if you'd like and we can talk this through while screensharing :)

>Fundraisers.fundraiser is an object that holds the transformed fundraisers for the specific date range and is not what is passed into the DB.

Is it ever set as the state though?

**Comment by HelloTiago** [comment]
The merge conflicts have been resolved and this work has been deployed to https://givepanel-dev3.firebaseapp.com.

**Comment by HelloTiago** [comment]
@jonrandahl This is where the fields inside CardDetails were duplicated. I've just fixed them and deployed this to https://givepanel-dev3.firebaseapp.com.

**Comment by jonrandahl** [comment]
@HelloTiago still seeing the alert on save?

https://www.loom.com/share/661d9736712942a2a7adb569e98ac182

**Comment by HelloTiago** [comment]
@jonrandahl Here's the loom you requested detailing the issue. As we discussed before, this is caused by the way we're loading and processing the Fundraiser/CardDetails data and state. I'm not sure how to implement a fix with the current data processing implementation, hopefully you guys have some ideas!

https://www.loom.com/share/7e3fd2e43321432a84dc0e244c674ef3

**Comment by jonrandahl** [comment]
@HelloTiago, the "state" is actually a value from the parent component passed down as a prop. It seems to me that this is where the issue is - that the parent component is not aware of the `isAlertOpen` nor should it be? I think we need to look at this from the parent component to see what is happening there when it passes things down? Happy to discuss this further on Slack!

**Pull request merged**
