### PR TITLE
Fix the View Donor List filtering

### PR DESCRIPTION
**Pull request by HelloTiago**
Relates to #297 - fixed a typo.

### CODE REVIEW

**Comment by jonrandahl** [comment]
@HelloTiago I'm still not seeing this on either the public url or my own instance where I applied your change:

```
  gotTransactions(transactions) {
    let transactionsData = transactions;

    const cid = queryString.parse(this.props.location.search).campaign_id;

    // If the URL has a Campaign ID, filter the transactions by it
    if (cid) {
      transactionsData = transactionsData.filter(t => t.campaign.id === parseInt(cid));
    }

    this.setState({
      transactions: transactionsData || [],
      filteredTransactions: transactionsData || []
    });

    this.props.dispatch(hideLoading());
  }

```

Can we catch up after lunch after 2pm?

**Comment by HelloTiago** [comment]
@jonrandahl I didn't deploy this to the public URL as there was/is other work you wanted to see there and we can only have one branch deployed at the same time on a public URL :)

As to why it didn't work on your instance, have you changed anything else that could impact the transactions load on the Donations page? I've triple checked this just now and it's working correctly locally.

If you checkout this branch and test it locally, does it work for you? If so the issue is related to some other work that I don't have on this branch yet in which case we can chat and take a look at what that might be. If it doesn't work on this branch either, let's also chat as I can't replicate that locally.

**Comment by jonrandahl** [comment]
@HelloTiago can you push this now to your public instance and then commit the changes here, I can then compare your code to mine and see what's going on!

**Comment by HelloTiago** [comment]
@jonrandahl I just deployed #267 to my public URL and it includes the changes on this PR. https://givepanel-dev3.firebaseapp.com/

**Comment by HelloTiago** [comment]
@jonrandahl This has been fixed. The Donations data wasn't loading because we weren't waiting long enough for `this.props.uid` to be set before calling in the `ChronologicalTrasactionsData.setup` method. I've moved this call into `componentDidUpdate` and if the UID is different during an update (which it is when the component mounts and then when the data comes in) it executes the setup method.

I've merged this fix into my other currently open PR as well, #267 , which has the exact same set of changes as this one *plus* the "Back to Fundraisers" link but that's it, so once this one gets merged in you can merge the other one right away.

I've deployed this one to my public URL: https://givepanel-dev3.firebaseapp.com/

**Comment by jonrandahl** [comment]
@HelloTiago I've checked your code and it's working great - however - can you please ensure the Production key is pointing to your public instance and not the staging/demo/or live ones when you deploy to dev3?

```
// "production" is relative to the instance
if (process.env.NODE_ENV === 'production') {
  // module.exports = require("./keys/prod");     // Live
  // module.exports = require("./keys/demo");     // Demo
  // module.exports = require("./keys/stage");    // Staging
  module.exports = require("./keys/dev3");     // Dev 3
  // module.exports = require("./keys/dev2");     // Dev 2
  // module.exports = require("./keys/dev1");     // Dev 1
} else {
  module.exports = require('./keys/dev3');
}

```

If your Production key is not pointing correctly then there's a possibility of cross-site pollution as changes would reflect on both sites which may or may not be an issue.

Thanks for this nonetheless!

**Pull request merged**
