### PR TITLE
Added the capability to filter Fundraisers by Labels

### PR DESCRIPTION
**Pull request by HelloTiago**
Relates to #85.

### CODE REVIEW

**Comment by HelloTiago** [comment]
@jonrandahl This one's ready to be merged. Doesn't include any changes to Donations, strictly limited to Fundraisers.

**Comment by HelloTiago** [comment]
@jonrandahl Thanks for catching this Jon! I've just pushed an update that fixes this.

**Comment by jonrandahl** [comment]
@HelloTiago, I've merged this branch into the latest staging branch and tested locally and we are so close!

Please refer to the loom to see what the remaining issue is:

https://www.useloom.com/share/85f95b3e916546d59b40068804547606

**Comment by jonrandahl** [comment]
image
Does it seem that the file conflicts merge haven't worked as planned?

**Comment by HelloTiago** [comment]
@jonrandahl The screenshot above relates to #306, not to this ticket. This ticket has been completed though and is ready to be reviewed. I have another PR deployed to the public URL for preview so I can't deploy this one simultaneously.

**Comment by HelloTiago** [comment]
@jonrandahl As requested this has been deployed to dev3: https://givepanel-dev3.firebaseapp.com

**Pull request merged**
